FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
WORKDIR /usr/local/app/

RUN apt-get update \
    && apt-get install -y curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -Ls https://github.com/block-core/blockcore-status/releases/download/#{VERSION}#/blockcore.status-#{VERSION}#-linux-x64.tar.gz \
    | tar -xvz -C .

EXPOSE 5050
ENTRYPOINT ["dotnet", "blockcore.status.dll"]
