name: Build and Release Docker Image

on:
  release:
    types: [published, prereleased]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            6.0.x

      - name: Log Variables
        run: |
          echo "action - ${{ github.event.action }}"
          echo "url - ${{ github.event.release.url }}"
          echo "assets_url - ${{ github.event.release.assets_url }}"
          echo "id - ${{ github.event.release.id }}"
          echo "tag_name - ${{ github.event.release.tag_name }}"
          echo "assets - ${{ github.event.assets }}"
          echo "assets[0] - ${{ github.event.assets[0] }}"

      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/Dockerfile.Release"]'
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Build the Docker container image for Blockcore Status
        run: docker build -f "./src/Blockcore.status/Dockerfile.Release" -t blockcore/status:latest -t blockcore/status:${{ github.event.release.tag_name }} --label "unstable=true" "."

      - name: Login and Push to Docker Registry
        run: |
          docker login -u "sondreb" -p "${{secrets.DOCKER_KEY}}"
          docker push --all-tags blockcore/status

      # - name: Login and Push to GitHub Docker Registry
      #   run: |
      #     docker login docker.pkg.github.com -u "blockcore-status" -p "${{secrets.GITHUB_TOKEN}}"
      #     docker push docker.pkg.github.com/block-core/blockcore-status/blockcorestatus:latest
